// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bidmachine/protobuf/extensions.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class ADCOMAd_Event;
@class BDMPlacementExt_CachedPlacement;
@class GPBAny;
GPB_ENUM_FWD_DECLARE(ADCOMApiFramework);

NS_ASSUME_NONNULL_BEGIN

#pragma mark - BDMExtensionsRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface BDMExtensionsRoot : GPBRootObject
@end

#pragma mark - BDMRequestExt

typedef GPB_ENUM(BDMRequestExt_FieldNumber) {
  BDMRequestExt_FieldNumber_SellerId = 1,
};

@interface BDMRequestExt : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *sellerId;

@end

#pragma mark - BDMPlacementExt

typedef GPB_ENUM(BDMPlacementExt_FieldNumber) {
  BDMPlacementExt_FieldNumber_AdSpaceId = 1,
  BDMPlacementExt_FieldNumber_CacheArray = 2,
};

/**
 * Layer-4 Placement Subtype Object Extension
 **/
@interface BDMPlacementExt : GPBMessage

/**
 * Ad Exchange ad space id
 * TODO: more suitable name - placement_id, tagid
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *adSpaceId;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<BDMPlacementExt_CachedPlacement*> *cacheArray;
/** The number of items in @c cacheArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger cacheArray_Count;

@end

#pragma mark - BDMPlacementExt_CachedPlacement

typedef GPB_ENUM(BDMPlacementExt_CachedPlacement_FieldNumber) {
  BDMPlacementExt_CachedPlacement_FieldNumber_Api = 1,
  BDMPlacementExt_CachedPlacement_FieldNumber_PriceEstimate = 2,
  BDMPlacementExt_CachedPlacement_FieldNumber_Tokens = 3,
  BDMPlacementExt_CachedPlacement_FieldNumber_ExtArray = 5,
};

@interface BDMPlacementExt_CachedPlacement : GPBMessage

/** SDK technology */
@property(nonatomic, readwrite) enum ADCOMApiFramework api;

/** Estimated price, calculated externally */
@property(nonatomic, readwrite) double priceEstimate;

/** Credentials obtained on client from SDK technology */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableDictionary<NSString*, NSString*> *tokens;
/** The number of items in @c tokens without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger tokens_Count;

/** Optional SDK-specific extensions */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<GPBAny*> *extArray;
/** The number of items in @c extArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger extArray_Count;

@end

/**
 * Fetches the raw value of a @c BDMPlacementExt_CachedPlacement's @c api property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t BDMPlacementExt_CachedPlacement_Api_RawValue(BDMPlacementExt_CachedPlacement *message);
/**
 * Sets the raw value of an @c BDMPlacementExt_CachedPlacement's @c api property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetBDMPlacementExt_CachedPlacement_Api_RawValue(BDMPlacementExt_CachedPlacement *message, int32_t value);

#pragma mark - BDMAdExt

typedef GPB_ENUM(BDMAdExt_FieldNumber) {
  BDMAdExt_FieldNumber_Tokens = 1,
  BDMAdExt_FieldNumber_SkipAfter = 2,
  BDMAdExt_FieldNumber_AutoClose = 3,
  BDMAdExt_FieldNumber_EventArray = 4,
};

@interface BDMAdExt : GPBMessage

/** Credentials obtained on server to feed in SDK technology */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableDictionary<NSString*, NSString*> *tokens;
/** The number of items in @c tokens without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger tokens_Count;

/** Number of seconds a creative must play before the placement enables skipping. */
@property(nonatomic, readwrite) uint32_t skipAfter;

/** Auto-close creative upon completion */
@property(nonatomic, readwrite) BOOL autoClose;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<ADCOMAd_Event*> *eventArray;
/** The number of items in @c eventArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger eventArray_Count;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
