// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bidmachine/protobuf/init.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class ADCOMAd_Event;
@class ADCOMContext_Geo;
GPB_ENUM_FWD_DECLARE(ADCOMConnectionType);
GPB_ENUM_FWD_DECLARE(ADCOMDeviceType);
GPB_ENUM_FWD_DECLARE(ADCOMOS);

NS_ASSUME_NONNULL_BEGIN

#pragma mark - BDMInitRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface BDMInitRoot : GPBRootObject
@end

#pragma mark - BDMInitRequest

typedef GPB_ENUM(BDMInitRequest_FieldNumber) {
  BDMInitRequest_FieldNumber_SellerId = 1,
  BDMInitRequest_FieldNumber_Bundle = 2,
  BDMInitRequest_FieldNumber_Os = 3,
  BDMInitRequest_FieldNumber_Osv = 4,
  BDMInitRequest_FieldNumber_Geo = 5,
  BDMInitRequest_FieldNumber_Sdk = 6,
  BDMInitRequest_FieldNumber_Sdkver = 7,
  BDMInitRequest_FieldNumber_Ifa = 8,
  BDMInitRequest_FieldNumber_DeviceType = 9,
  BDMInitRequest_FieldNumber_Contype = 10,
};

@interface BDMInitRequest : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *sellerId;

/** Bundle or package name of the app. */
@property(nonatomic, readwrite, copy, null_resettable) NSString *bundle;

/** Device operating system. */
@property(nonatomic, readwrite) enum ADCOMOS os;

/** Device operating system version. */
@property(nonatomic, readwrite, copy, null_resettable) NSString *osv;

/** Location of the device. */
@property(nonatomic, readwrite, strong, null_resettable) ADCOMContext_Geo *geo;
/** Test to see if @c geo has been set. */
@property(nonatomic, readwrite) BOOL hasGeo;

/** Name of ad mediation partner, SDK technology, or player responsible for rendering ad. */
@property(nonatomic, readwrite, copy, null_resettable) NSString *sdk;

/** Version of the SDK specified in the "sdk" attribute. */
@property(nonatomic, readwrite, copy, null_resettable) NSString *sdkver;

/** ID sanctioned for advertiser use in the clear (i.e., not hashed). */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ifa;

/** The general type of device. */
@property(nonatomic, readwrite) enum ADCOMDeviceType deviceType;

/** Network connection type. */
@property(nonatomic, readwrite) enum ADCOMConnectionType contype;

@end

/**
 * Fetches the raw value of a @c BDMInitRequest's @c os property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t BDMInitRequest_Os_RawValue(BDMInitRequest *message);
/**
 * Sets the raw value of an @c BDMInitRequest's @c os property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetBDMInitRequest_Os_RawValue(BDMInitRequest *message, int32_t value);

/**
 * Fetches the raw value of a @c BDMInitRequest's @c deviceType property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t BDMInitRequest_DeviceType_RawValue(BDMInitRequest *message);
/**
 * Sets the raw value of an @c BDMInitRequest's @c deviceType property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetBDMInitRequest_DeviceType_RawValue(BDMInitRequest *message, int32_t value);

/**
 * Fetches the raw value of a @c BDMInitRequest's @c contype property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t BDMInitRequest_Contype_RawValue(BDMInitRequest *message);
/**
 * Sets the raw value of an @c BDMInitRequest's @c contype property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetBDMInitRequest_Contype_RawValue(BDMInitRequest *message, int32_t value);

#pragma mark - BDMInitResponse

typedef GPB_ENUM(BDMInitResponse_FieldNumber) {
  BDMInitResponse_FieldNumber_Endpoint = 1,
  BDMInitResponse_FieldNumber_EventArray = 2,
};

@interface BDMInitResponse : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *endpoint;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<ADCOMAd_Event*> *eventArray;
/** The number of items in @c eventArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger eventArray_Count;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
