# Defines
APP_IDENTIFIER  = "com.bidmachine.sample"
SCHEME          = "Sample"
SLACK_URL       = "SLACK URL"
TYPE            = "appstore"
IPA_PATH        = "./fastlane/build"
CERTIFICATES    = "./fastlane/cers_and_profiles"
USER            = "USER EMAIL"
TEAM            = "TEAM"
PASSWORD        = "YOUR PASSWORD"
TESTFLIGHT_TEAM = "YOUR TEAM"
DESCRIPTION     = "Upload new BidMachine Sample!"

# Congig
fastlane_version "2.68.2"
default_platform :ios

def signing
  cert(
      output_path: CERTIFICATES,
      username: USER,
      team_id: TEAM
      )
  sigh(
      force: true,
      app_identifier: APP_IDENTIFIER,
      team_id: TEAM,
      username: USER,
      output_path: CERTIFICATES
      )
end

def build_example
  gym(
      scheme: SCHEME,
      silent: true,
      output_directory: IPA_PATH
    )
end

def upload_example_to_testflight
  testflight(
    app_identifier: APP_IDENTIFIER,
    username: USER,
    team_id: TESTFLIGHT_TEAM,
    skip_waiting_for_build_processing: true,
    beta_app_description: DESCRIPTION
    )
end

platform :ios do
  before_all do
    ENV["SLACK_URL"] = SLACK_URL
    ENV["GYM_PROVISIONING_PROFILE_PATH"] = CERTIFICATES
    ENV["FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD"] = PASSWORD
    cocoapods
  end

  desc "Runs all the tests"
  lane :test do
    run_tests
  end

  desc "Submit a new Beta Build to Apple TestFlight for QA testing"
  lane :qa do
    signing
    # Build app
    build_example
    # Upload to testflight
    upload_example_to_testflight
    # Increnment build number
    increment_build_number(
      xcodeproj: "./Sample/Sample.xcodeproj"
      )
  end

  after_all do |lane|
    slack(
      message: "Successfully deployed new BidMachine Sample App Update.",
      success: true
    )
    sh("osascript -e 'display notification \"Complete deployment\" with title \"Fastlane\"'")
  end

  error do |lane, exception|
    sh("osascript -e 'display notification \"BidMachine Sample deployment failed\" with title \"Fastlane\"'")
  end
end