// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bidmachine/protobuf/extensions.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class GPBEnumDescriptor;
@class ADCOMAd_Event;
@class BDMPlacementExtension_CachedPlacement;
@class GPBAny;
GPB_ENUM_FWD_DECLARE(ADCOMApiFramework);

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum BDMEventTypeExtended

/**
 * Use for tracking events
 * Insert this codes in ВМ_EVENT_CODE macros in error tracking
 **/
typedef GPB_ENUM(BDMEventTypeExtended) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  BDMEventTypeExtended_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  BDMEventTypeExtended_EventTypeExtendedInvalid = 0,

  /** Ad lifecycle and interaction trackers */
  BDMEventTypeExtended_EventTypeExtendedLoaded = 500,
  BDMEventTypeExtended_EventTypeExtendedImpression = 501,
  BDMEventTypeExtended_EventTypeExtendedViewable = 502,
  BDMEventTypeExtended_EventTypeExtendedClick = 503,
  BDMEventTypeExtended_EventTypeExtendedClosed = 504,
  BDMEventTypeExtended_EventTypeExtendedDestroyed = 505,

  /** Ad progress trackers */
  BDMEventTypeExtended_EventTypeExtendedStarted = 600,
  BDMEventTypeExtended_EventTypeExtendedFirstQuartile = 601,
  BDMEventTypeExtended_EventTypeExtendedMidpoint = 602,
  BDMEventTypeExtended_EventTypeExtendedThirdQuartile = 602,
  BDMEventTypeExtended_EventTypeExtendedCompleted = 603,

  /** Error tracker */
  BDMEventTypeExtended_EventTypeExtendedError = 1000,
  BDMEventTypeExtended_EventTypeExtendedTrackingError = 1001,

  /** deprecated */
  BDMEventTypeExtended_EventTypeExtendedFill DEPRECATED_ATTRIBUTE = 500,
  BDMEventTypeExtended_EventTypeExtendedFinish DEPRECATED_ATTRIBUTE = 502,
};

GPBEnumDescriptor *BDMEventTypeExtended_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL BDMEventTypeExtended_IsValidValue(int32_t value);

#pragma mark - Enum BDMActionType

/**
 * Use for tracking process errors
 * insert this codes in ВМ_ACTION_CODE macros in error
 **/
typedef GPB_ENUM(BDMActionType) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  BDMActionType_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  BDMActionType_ActionTypeTypeInvalid = 0,

  /** Ad lifecycle */
  BDMActionType_ActionTypeLoading = 500,
  BDMActionType_ActionTypeShowing = 501,
  BDMActionType_ActionTypeViewing = 502,
  BDMActionType_ActionTypeClicking = 503,
  BDMActionType_ActionTypeClosing = 504,
  BDMActionType_ActionTypeDestroying = 505,
};

GPBEnumDescriptor *BDMActionType_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL BDMActionType_IsValidValue(int32_t value);

#pragma mark - Enum BDMErrorReason

/**
 * Use for tracking errors of both error types
 * insert this codes in ВМ_ERROR_REASON macros in error
 **/
typedef GPB_ENUM(BDMErrorReason) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  BDMErrorReason_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  BDMErrorReason_ErrorReasonInvalid = 0,
  BDMErrorReason_ErrorReasonNoConnection = 100,
  BDMErrorReason_ErrorReasonBadContent = 101,
  BDMErrorReason_ErrorReasonTimeout = 102,
  BDMErrorReason_ErrorReasonNoContent = 103,
  BDMErrorReason_ErrorReasonHandledException = 104,
  BDMErrorReason_ErrorReasonWasClosed = 105,
  BDMErrorReason_ErrorReasonWasDestroyed = 106,
  BDMErrorReason_ErrorReasonWasExpired = 107,
  BDMErrorReason_ErrorReasonInternal = 108,
  BDMErrorReason_ErrorReasonHTTPServerError = 109,
  BDMErrorReason_ErrorReasonHTTPBadRequest = 110,
};

GPBEnumDescriptor *BDMErrorReason_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL BDMErrorReason_IsValidValue(int32_t value);

#pragma mark - Enum BDMApiFrameworkExtended

typedef GPB_ENUM(BDMApiFrameworkExtended) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  BDMApiFrameworkExtended_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  BDMApiFrameworkExtended_ApiFrameworkExtendedInvalid = 0,
  BDMApiFrameworkExtended_ApiFrameworkExtendedAdcolony = 500,
  BDMApiFrameworkExtended_ApiFrameworkExtendedApplovin = 510,
  BDMApiFrameworkExtended_ApiFrameworkExtendedSmaato = 520,
  BDMApiFrameworkExtended_ApiFrameworkExtendedVungle = 530,
  BDMApiFrameworkExtended_ApiFrameworkExtendedMytarget = 540,
  BDMApiFrameworkExtended_ApiFrameworkExtendedTapjoy = 550,
  BDMApiFrameworkExtended_ApiFrameworkExtendedPubnative = 560,
};

GPBEnumDescriptor *BDMApiFrameworkExtended_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL BDMApiFrameworkExtended_IsValidValue(int32_t value);

#pragma mark - BDMExtensionsRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface BDMExtensionsRoot : GPBRootObject
@end

#pragma mark - BDMRequestExtension

typedef GPB_ENUM(BDMRequestExtension_FieldNumber) {
  BDMRequestExtension_FieldNumber_SellerId = 1,
  BDMRequestExtension_FieldNumber_SellerData = 2,
};

@interface BDMRequestExtension : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *sellerId;

/** Extra data */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableDictionary<NSString*, NSString*> *sellerData;
/** The number of items in @c sellerData without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger sellerData_Count;

@end

#pragma mark - BDMPlacementExtension

typedef GPB_ENUM(BDMPlacementExtension_FieldNumber) {
  BDMPlacementExtension_FieldNumber_AdSpaceId = 1,
  BDMPlacementExtension_FieldNumber_CacheArray = 2,
};

/**
 * Layer-4 Placement Subtype Object Extension
 **/
@interface BDMPlacementExtension : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *adSpaceId DEPRECATED_ATTRIBUTE;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<BDMPlacementExtension_CachedPlacement*> *cacheArray;
/** The number of items in @c cacheArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger cacheArray_Count;

@end

#pragma mark - BDMPlacementExtension_CachedPlacement

typedef GPB_ENUM(BDMPlacementExtension_CachedPlacement_FieldNumber) {
  BDMPlacementExtension_CachedPlacement_FieldNumber_Api = 1,
  BDMPlacementExtension_CachedPlacement_FieldNumber_PriceEstimate = 2,
  BDMPlacementExtension_CachedPlacement_FieldNumber_Tokens = 3,
  BDMPlacementExtension_CachedPlacement_FieldNumber_ExtArray = 5,
};

@interface BDMPlacementExtension_CachedPlacement : GPBMessage

/** SDK technology */
@property(nonatomic, readwrite) enum ADCOMApiFramework api;

/** Estimated price, calculated externally */
@property(nonatomic, readwrite) double priceEstimate;

/** Credentials obtained on client from SDK technology */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableDictionary<NSString*, NSString*> *tokens;
/** The number of items in @c tokens without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger tokens_Count;

/** Optional SDK-specific extensions */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<GPBAny*> *extArray;
/** The number of items in @c extArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger extArray_Count;

@end

/**
 * Fetches the raw value of a @c BDMPlacementExtension_CachedPlacement's @c api property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t BDMPlacementExtension_CachedPlacement_Api_RawValue(BDMPlacementExtension_CachedPlacement *message);
/**
 * Sets the raw value of an @c BDMPlacementExtension_CachedPlacement's @c api property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetBDMPlacementExtension_CachedPlacement_Api_RawValue(BDMPlacementExtension_CachedPlacement *message, int32_t value);

#pragma mark - BDMAdExtension

typedef GPB_ENUM(BDMAdExtension_FieldNumber) {
  BDMAdExtension_FieldNumber_Tokens = 1,
  BDMAdExtension_FieldNumber_Preload = 2,
  BDMAdExtension_FieldNumber_SkipAfter = 3,
  BDMAdExtension_FieldNumber_ViewabilityTimeThreshold = 4,
  BDMAdExtension_FieldNumber_ViewabilityPixelThreshold = 5,
  BDMAdExtension_FieldNumber_ViewabilityDurationThreshold = 6,
  BDMAdExtension_FieldNumber_EventArray = 7,
};

@interface BDMAdExtension : GPBMessage

/** Credentials obtained on server to feed in SDK technology */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableDictionary<NSString*, NSString*> *tokens;
/** The number of items in @c tokens without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger tokens_Count;

/** Preload ad's markup before rendering with ad framework */
@property(nonatomic, readwrite) BOOL preload;

/** Number of seconds an ad must load or play before user can skip this ad */
@property(nonatomic, readwrite) uint32_t skipAfter;

/** Minimal time in view for ad to be considered viewable */
@property(nonatomic, readwrite) uint32_t viewabilityTimeThreshold;

/**
 * Minimal percentage of the pixels in view for ad to be considered viewable
 * 0.5 = 50% of pixels
 **/
@property(nonatomic, readwrite) float viewabilityPixelThreshold;

/**
 * Minimal completed duration for video ad to be consideder viewable
 * 0.5 = 50% of video duration
 **/
@property(nonatomic, readwrite) float viewabilityDurationThreshold;

/** List of custom tracking events */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<ADCOMAd_Event*> *eventArray;
/** The number of items in @c eventArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger eventArray_Count;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
